# Generated by Django 4.0.1 on 2022-01-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='shipping_country',
            new_name='country',
        ),
    ]
